### ISSUE TITLE
Past due times are not showing as red

### ISSUE THREAD

**Issue by scottrobertson** [DamascenoRafael/reminders-menubar#10]
Did you end up implementing this in #6? If so, it's not working.

Note: it's currently 11:41

![image](https://user-images.githubusercontent.com/68361/105840760-702e1480-5fcb-11eb-827f-b21bbda9f42e.png)

**Comment by scottrobertson** [comment]
Oh, i just hid a list, and it seems to have switched them to red. Maybe it had not reloaded or something?

**Comment by DamascenoRafael** [comment]
I hadn't noticed that, thanks for the feedback!

The View has nothing to indicate that it needs to be reloaded. I'll have to look for something to trigger this reload so that the text changes to expired reminders.

Probably the same will happen when the text needs to change from "Tomorrow" to "Today", for example. 😞 

I'll take a look after work.

**Comment by DamascenoRafael** [comment]
Hey, I believe that the problem with the text not changing to red has been solved!

In addition, there is now an observer and any changes to Apple Reminders will automatically reflect in the App 🎉 

I'm not sure if there is still a problem when the text needs to change between a date, "Tomorrow", "Today" etc. because if no other reminder triggers the observer then the View probably won't update. I will try to investigate whether this happens later.
