### ISSUE TITLE
Add an option to show all reminders for today and reminders without date

### ISSUE THREAD

**Issue by samcarter** [DamascenoRafael/reminders-menubar#102]
I'm using the `today` view in order to not see reminders for future dates. It would be nice to have an option to see all reminders for today as well as all reminders without date (so that all future reminders are hidden and all other are visible).

<img width="126" alt="Screenshot 2023-02-03 at 13 15 58" src="https://user-images.githubusercontent.com/43832342/216601639-37e6fea8-da92-4679-a209-abd4a07cde83.png">

... or alternatively allow to set a default date so one does not have to click on the `add date` button every time one creates a new reminder in order to get it in the "today" list

<img width="332" alt="Screenshot 2023-02-03 at 13 14 22" src="https://user-images.githubusercontent.com/43832342/216602891-1744aabe-19ec-4dc8-a138-e91e2f7a2170.png">

Reminders Menu Bar version: 1.13.0
macOS: 11.7.2

**Comment by DomizianoScarcelli** [comment]
> I'm using the `today` view in order to not see reminders for future dates. It would be nice to have an option to see all reminders for today as well as all reminders without date (so that all future reminders are hidden and all other are visible).
> 
> <img alt="Screenshot 2023-02-03 at 13 15 58" width="126" src="https://user-images.githubusercontent.com/43832342/216601639-37e6fea8-da92-4679-a209-abd4a07cde83.png">
> 
> ... or alternatively allow to set a default date so one does not have to click on the `add date` button every time one creates a new reminder in order to get it in the "today" list
> 
> <img alt="Screenshot 2023-02-03 at 13 14 22" width="332" src="https://user-images.githubusercontent.com/43832342/216602891-1744aabe-19ec-4dc8-a138-e91e2f7a2170.png">
> 
> Reminders Menu Bar version: 1.13.0 macOS: 11.7.2

In this pull request https://github.com/DamascenoRafael/reminders-menubar/pull/105 I added the possibility to specify the date with natural language, so you can say "Do something this afternoon" and it will set the date and time. In the meantime, a workaround is to create a "Generic todo" list that you put as default, meaning you select that from the dropdown menu on the right, and add the "Generic todo" to the list that is always visible in the app. This way, you'll be able to see those reminders even if they don't have a date.

**Comment by samcarter** [comment]
@DomizianoScarcelli  Thanks you very much for your suggestions! 

I tried the workaround with the two lists. For me this has the disadvantage that the items of the Generic todo list won't be included in the nice counter in the menu bar. 

I'm very much looking forward to your new natural language feature, this will at least save the hassle of having to switch to the mouse just to click on the date. 

Thanks for working on this app!

**Comment by DomizianoScarcelli** [comment]
For now, the feature in English is pretty stable, so if you don't want to wait for the review of the owner and eventually the merge, you can clone the fork with the changes and build the app locally with XCode 😄

**Comment by DamascenoRafael** [comment]
Hey @samcarter, it seems to me that you are asking for 2 different features.

About setting a new reminder to be for today by default, in the next version there will be an option so that when typing a new reminder the date is auto-suggested as today:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/9842644/221477562-4267ebb3-90c2-4750-a297-2f2bfd28b6b8.png">

As for seeing all reminders without date, for now the easy way seems to be creating a generic list of all those reminders. Does this way work for you? Apple Reminders supports smart lists where it would be possible to create a filter for it, but it is still not possible to view smart lists in the Reminders Menu Bar (Apple APIs do not allow easy access to this info).

Regarding the counter next to the menu bar icon, what would you like to see is the total number of unfinished reminders (including today, tomorrow, all reminders with a date, and all reminders without a date)?

Let me know if I understand correctly. We can try to evaluate how to improve this experience.

**Comment by samcarter** [comment]
@DamascenoRafael Oh, the auto-suggest feature looks brilliant! Thanks a lot! This will solve all my problems. 

I was indeed suggesting two different ways to solve my problem, having one of them (the auto-suggest) completely solves my problem. 

I'm very much looking forward to your next release for all the nice new features!

**Comment by DamascenoRafael** [comment]
@samcarter I'm glad to hear that this will solve your problem :)
Version 1.14.0 is now available 📦 ✨ 

Please let me know if you have any feedback or suggestions for improvement.

**Comment by samcarter** [comment]
@DamascenoRafael  Works brilliantly! Thank you so much!
