### ISSUE TITLE
I would like to see all reminders on the menubar rather than just the reminders due today

### ISSUE THREAD

**Issue by TheAbubakrAbu** [DamascenoRafael/reminders-menubar#127]
Title.

**Comment by DamascenoRafael** [comment]
@TheAbubakrAbu are you referring to the counter that appears in the menu bar?

It currently shows the count of reminders that are due today, but I think we could add the option to count all reminders (since that would also include those that are due today).

**Comment by DamascenoRafael** [comment]
@TheAbubakrAbu Please check the v1.17.0 release 📦 
There is now an option to choose between today's count or all reminders.

**Comment by TheAbubakrAbu** [comment]
Thank you so much! This sounds great!

**Comment by TheJoeSop** [comment]
Not sure if this should be a new issue or not.  Could the counter just show the number of items in the currently displayed reminders list?  I've hid all the other ones.  I have a lot of various lists in Reminders but only use my to-do list for work in the app, so I'd want to see that as 13, rather than the 318 across all lists.
