### ISSUE TITLE
Request: make the date preview under the reminder title localisable

### ISSUE THREAD

**Issue by katullo11** [DamascenoRafael/reminders-menubar#150]
As of now, the date under the reminder title doesn't pick up the language chosen for the app, it is always English.

**Comment by DamascenoRafael** [comment]
Thanks for the feedback. Trying to understand how this can be fixed.

**Comment by DamascenoRafael** [comment]
@katullo11 just to confirm, you are referring to the date showed when creating a reminder, as highlighted in the image below, right? I think I found a fix for this, I'm running some tests.

<img width="622" alt="image" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/13dafd86-f35e-4352-88a7-af9567df8391">

**Comment by katullo11** [comment]
@DamascenoRafael yes, but I'm also referring to when the reminder has already been created. The date under its name will always be in English.

**Comment by DamascenoRafael** [comment]
@katullo11 I believe that the date for created reminders is already appearing according to the language selected in the App. What happens is that after changing the language it may be necessary to close and reopen the app or at least hover the mouse over the elements so that the text is updated. Examples below for System (en), Portuguese and Dutch. Let me know if there is any behavior in this regard that does not seem correct.

- system (English)
  <img width="450" alt="Screenshot 2023-09-27 at 21 03 31" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/6852ee43-349f-4792-ab3d-62350e84bd93">

- Portuguese
  <img width="450" alt="Screenshot 2023-09-27 at 21 04 23" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/0712c77d-4558-4270-86b5-ec9623a977c8">

- Dutch
  <img width="450" alt="Screenshot 2023-09-27 at 21 05 27" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/29f2dd1d-4361-4136-adda-1cd068e78074">

**Comment by katullo11** [comment]
I have tried restarting and hovering, but the language stays in English even though I have set Italian as my primary system language. If I set the app's language to Italian, the dates do show correctly, so it may be related to an incorrect interpretation of the system language?

This is my system language configuration:
![87737](https://github.com/DamascenoRafael/reminders-menubar/assets/129339155/84b1f238-4109-4117-a9a6-feb61934dc7c)

This is the app's behaviour with "System language" set:
![33120](https://github.com/DamascenoRafael/reminders-menubar/assets/129339155/af7aec11-d6fa-4862-b066-fef821fc8900)

**Comment by DamascenoRafael** [comment]
To confirm, if you select Italian as your preferred language (and then close and reopen the app), can you see the dates as below?

<img width="548" alt="Screenshot 2023-09-28 at 23 50 55" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/65c7c0c5-9b81-4922-93cc-67412855185f">

From what I understand, the problem would only be when selecting the "Use system language" option, right?

**Comment by DamascenoRafael** [comment]
@katullo11 to confirm, if you select Italian as your preferred language (and then close and reopen the app), can you see the dates as below?

<img width="548" alt="Screenshot 2023-09-28 at 23 50 55" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/65c7c0c5-9b81-4922-93cc-67412855185f">

From what I understand, the problem would only be when selecting the "Use system language" option, right?

**Comment by katullo11** [comment]
@DamascenoRafael exactly. The problem only persists as long as I have "System Language" set.

**Comment by DamascenoRafael** [comment]
@katullo11, sorry, I know it's been a while. I think this is possibly fixed in version 1.22.0, could you please try it?

**Comment by katullo11** [comment]
No need to apologise. It seems to be fixed now! Thanks!
