### ISSUE TITLE
Time detected is incorrect in certain specific situations (even with auto-detect disabled) v1.20.0 (also existed on previous version)

### ISSUE THREAD

**Issue by pearresearch** [DamascenoRafael/reminders-menubar#152]
https://github.com/DamascenoRafael/reminders-menubar/assets/110237207/7f9e9632-ae11-45eb-a498-3b67a6e06bda

The time detected once the first digit is entered is not updated upon entering the second digit. For instance, in the video, my time currently is **past 1:00PM** on **6th July**. Hence, when I attempt to enter a time including 1, it automatically switches to the next day. **Both 1:00AM and 1:00PM have passed of July 6**. 

But this means I cannot enter 10:00 PM ('1' followed be a '0'), since entering 1 automatically throws it to the next day. But I can successfully enter 4:00 PM, since 4 has not passed yet (4:00 AM has passed).  I'm not a dev, so I may not be sure how this is interpreted, but I am trying my best to explain in variants through logical understanding.

**Comment by DamascenoRafael** [comment]
Hey @pearresearch, sorry for taking so long to respond. Thanks for your feedback.
About this issue, let me explain what was happening and what I will do to fix it.

We are using Apple's NSDataDetector API to detect date, but we are making some adjustments to the date returned by the API to try to bring a better experience. It turns out that these adjustments bring several edge cases, so I will simplify these adjustments as much as possible to avoid these edge cases.

About the case you recorded on **July 6th at 1:01pm**:
- When you type "today at 1", the API doesn't tell you that you specified "today", but we know that is being interpreted as "1pm". Since **1pm is not in the future**, we are assuming that you may have typed something like "Review BMC at 1pm" and so we are using the next day (July 7th). This way it is a future date and not a past date.
- When you change it to "today at 4", as **4pm is in the future** we assume the date is today without adjustment. It is worth pointing out that the date is being presented as mm/dd/yyyy, so 6/7/2023 is July 6th.

I know it sounds confusing and I understand that the final experience as you demonstrated is not ideal. I will simplify these adjustments a lot and I believe it will bring a better experience. 

I will commit the fix soon and close the issue. This fix will be in the next release! You should see the changes once the next version is released.
