### ISSUE TITLE
Icon in menu bar not showing

### ISSUE THREAD

**Issue by Greenyleen** [DamascenoRafael/reminders-menubar#156]
Hello !
I  would love to use this app, i successfully downloaded it and is now in my app folder. Unfortunately it's not showing in my menu bar. I have zero knowledge in coding so i'm lost. If someone could help me ^^
Thanks

**Comment by DamascenoRafael** [comment]
Hey @Greenyleen, I am sorry that you are having this issue.

Couple questions that can help clarify what is happening:
- Can you give more details of what happens when you try to open the app?
- Did you download the app or install it via brew?
- If something appears in the menu bar can you please send a screenshot of it?
- Can you also confirm (or send a screenshot of) how the app appears in your app folder?

**Comment by DamascenoRafael** [comment]
Closing this since I haven't had updates.
I'll be happy to open it again if there's more information to be able to investigate and address the issue.
