### ISSUE TITLE
[OpenCore Legacy Patcher] "Access to Reminders is not enabled for Reminders MenuBar"

### ISSUE THREAD

**Issue by gvmelbrty** [DamascenoRafael/reminders-menubar#159]
Attempting to install RMB on MacOS Ventura. When I click on the RMB icon in the menu bar after installing, I get this message, "Access to Reminders is not enabled for Reminders MenuBar... Go to System Settings.. .."

Go to: System Settings -> Privacy & Security -> Reminders. .. Reminders MenuBar does not appear there.

Any ideas? Thanks

**Comment by DamascenoRafael** [comment]
Hey @gvmelbrty and @damaimaikou. Sorry to hear about your experiences.

If the app does not request authorization and the window saying that the app was not authorized appears, please note if there is a question mark button as in the image below. If there is an error message when requesting authorization this button should be available and when you click it you should have more information about why it is failing.

<img width="372" alt="Screenshot 2023-07-02 at 23 16 14" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/69df3b8a-17c0-4120-9947-55bffcad31b4">

Please let me know if the button appears and if so what is the error message.

**Comment by gvmelbrty** [comment]
My windows are shown below. .. No question mark. .. Full disclosure: Not sure if this matters, but I do operate with OpenCore Legacy patcher, which allows my older mac to run Ventura.

![Screenshot 2023-08-30 at 9 38 48 PM](https://github.com/DamascenoRafael/reminders-menubar/assets/14062191/7bf9145f-a5e5-4fda-9128-e00cf47a1076)
![Screenshot 2023-08-30 at 9 39 49 PM](https://github.com/DamascenoRafael/reminders-menubar/assets/14062191/9621e82c-a1de-416d-b972-587a0da39677)

**Comment by DamascenoRafael** [comment]
@gvmelbrty thanks for the info, I don't know if it could be related.

@damaimaikou can you let me know your macOS version and if you are using something like OpenCore Legacy Patcher?

@gvmelbrty would it be possible for you to download the repository and run it in Xcode so that we can try to investigate the authorization status further?

**Comment by damaimaikou** [comment]
I am using macOS 14 Sonoma beta7，and also using OpenCore Legacy Patcher.

**Comment by DamascenoRafael** [comment]
@gvmelbrty @damaimaikou, I have no experience with OpenCore Legacy Patcher, but from what I could find online, it seems that Reminders MenuBar is unable to request permissions due to this patcher.

There seem to be some workarounds for this, I'll try to give some directions, but I won't be able to test this on my machine.
Most online content mentions Camera or Mic permission, but Reminders permission should be similar (since everything relies on Apple API).

OpenCore Legacy Patcher documentation:
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-grant-special-permissions-to-apps-ie-camera-access-to-zoom

Some threads about this:
https://forums.macrumors.com/threads/camera-microphone-permissions-with-opencore-legacy-patcher-issue.2390550/
https://superuser.com/questions/1779925/macos-ventura-cant-give-permissions-opencore

TCCPlus repository:
https://github.com/jslegendre/tccplus

I'm not sure if TCCPlus still works or if it's reliable for new versions of macOS. I would suggest looking up some threads on the subject and if possible making a backup before trying commands that might affect the use of macOS.

If TCCPlus still works as expected, I believe the commands below should add the required permission:
```shell
cd ~/Downloads/
chmod +x tccplus
./tccplus add Reminders br.com.damascenorafael.reminders-menubar
```

Please let me know if you manage to add the permission this way or another. This will certainly help other users.

**Comment by damaimaikou** [comment]
@DamascenoRafael Thanks very much！💗

**Comment by damaimaikou** [comment]
@DamascenoRafael it works！

**Comment by DamascenoRafael** [comment]
@damaimaikou great! Did you use TCCPlus?

@gvmelbrty waiting for your confirmation if it also worked for you.

I will add a note about this into the README later.

**Comment by damaimaikou** [comment]
@DamascenoRafael yes，I used it TCCPlus，Following your method

**Comment by gvmelbrty** [comment]
> @damaimaikou great! Did you use TCCPlus?
> @gvmelbrty waiting for your confirmation if it also worked for you.

Success as well! .. Using the TCCPlus instructions you provided. .. You may want to mention in your note that instead of copy-paste-enter for all three Terminal commands at once, each line should be executed individually.. paste first line; hit enter.. paste 2nd line; hit enter.. etc. And in case it's not obvious, the TCCPlus file should be unziped and placed into the Downloads folder before executing the commands. 

Offering support for systems that are running OpenCore Legacy Patcher is definitely going above and beyond.. so thank you very much! .. Using your app now.. super cool having Reminders up in the menu bar.

**Comment by DamascenoRafael** [comment]
Great!! Thank you both for your help in investigating and testing the solution to this issue.
I hope you are enjoying the app :)

I've added new information to the README, including about this issue with the OpenCore Legacy Patcher.
https://github.com/DamascenoRafael/reminders-menubar/#permission-request
