### ISSUE TITLE
No subtasks

### ISSUE THREAD

**Issue by timlance** [DamascenoRafael/reminders-menubar#162]
For a few (several?) versions of Reminders the user can add "subtasks" to a Reminder. In Reminders-Menubar these subtasks are simply listed as the other tasks. The trouble is they are listed randomly. For example, I have a group of reminders for 'Home' with one reminder to finally replace some damn doorknobs - with subtasks of count, buy and install. In the listing for Home, among the other items there is doorknobs then among the others count, buy, and install are randomly listed - out of order and with other reminders interspersed. In a similar application, PopDo (on the MAS), subtasks are also not delineated as in Reminders.app proper but are listed right after the main reminder, i.e. I see Doorknobs then immediately count, buy, and install are listed correctly. PopDo's developer told me Apple does not supply a means to show subtasks in a sub-list.

**Comment by DamascenoRafael** [comment]
@timlance thanks for you feedback. This is something I wish I had made available in the app for a while. In fact, Apple does not provide access to this information through the API, but there are workarounds to access information that the API does not provide. I'm currently working on this, and I believe I can make it available in the next version of Reminders MenuBar.

Here's a sneak peak of it working:
<img width="775" alt="Screenshot 2023-09-24 at 22 39 34" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/b23c70df-65f0-43ad-a1ab-965adceded57">

There is already an older issue about this feature where I will post updates.
We can keep the discussion there: https://github.com/DamascenoRafael/reminders-menubar/issues/36 [Handle subtasks and subgroups (nested lists) in a nicer way](https://github.com/DamascenoRafael/reminders-menubar/issues/36).

**Comment by DamascenoRafael** [comment]
@timlance regarding the order of the reminders, it's not random, but I understand that due to the lack of the subtasks feature, a different ordering could be bad.

The adopted order is defined in: [ArrayEKReminder+Extension.swift](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menubar/Extensions/ArrayEKReminder%2BExtension.swift)

In summary:

- Uncompleted reminders appear first, followed by completed ones.
- Both are ordered according to priority (from high to none).
- In each priority, reminders with due date appear first, followed by undated reminders.
- For **uncompleted** reminders **with date** they are sorted in ascending order according to the due date (closest due dates first).
- For **uncompleted** reminders **without date** they are sorted in descending order according to creation date (new ones first).
- For **completed** reminders **with date** they are sorted in descending order according to the date they were completed (recently completed first).
- For **completed** reminders **without date**, they are sorted in descending order according to the creation date (new ones first).

If you find it necessary, you can open a new issue about the ordering of reminders. Some of the ordering decisions can become settings chosen by the user.

As this issue concerns subtasks I will mark this issue as a duplicate and close it.
Feel free to open other issues if necessary.
