### ISSUE TITLE
Add tooltip to folder button (which is next to each list)

### ISSUE THREAD

**Issue by oldsweatyman** [DamascenoRafael/reminders-menubar#192]
Forgive the stupidity, but, what does the little folder icon toggle do? On the right side of every category. Can't find a description anywhere.

Additionally, what does the circle (that is filled with an inner circle upon clicking) at the bottom do?

Edit: I see that the "folder" icon makes it so that this is the default category for new tasks. Would just be cool to have that explicit somewhere for people as dumb as myself.

**Comment by DamascenoRafael** [comment]
@oldsweatyman thanks for you feedback. You're right, the folder button on the right side of each category can be used to define where the reminders will be saved (as a quick access so you don't have to click on the button next to the text input and select your category from the list).

I will add a tooltip to this button so that a description of what it does appears during hover.

About the circle button at the bottom, it already has a tooltip. If you hover the button a description should appear:
<img width="435" alt="image" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/91cd6c52-f6d1-4c97-96f4-c002d7fbaf0b">

Let me know if you have any other questions.

**Comment by oldsweatyman** [comment]
Thank you for the excellent app and help!

**Comment by DamascenoRafael** [comment]
Keeping the issue open so it can be addressed soon.
