### ISSUE TITLE
Feature Request: Get reminders from different account

### ISSUE THREAD

**Issue by Abhijeet-AR** [DamascenoRafael/reminders-menubar#57]
Currently my mac doesn't have my apple account signed in, I want to get reminders from a different account. Can we have a sign in option to sign in to a different account.

**Comment by zydeico** [comment]
> Currently my mac doesn't have my apple account signed in, I want to get reminders from a different account. Can we have a sign in option to sign in to a different account.

The app depends of the reminders stored in iCloud account

**Comment by Abhijeet-AR** [comment]
Can I override the iCloud account that is present on the mac?

**Comment by DamascenoRafael** [comment]
Hi @Abhijeet-AR, I hope you were able to find the answer to this.
As mentioned above the app depends on the reminders that are synced by Apple Reminders.
I think that if you open _**System Settings/Preferences > Internet Accounts**_ and click on "_**Add Account...**_" you should be able to add a new iCould account and manage it so that the Reminders from that new account are synced.
I have never tried this so I can't confirm.

**Comment by DamascenoRafael** [comment]
Closing this as it is related to macOS settings and not the app.
