### ISSUE TITLE
Feature Request: Sort reminder lists based on order in Reminder.app

### ISSUE THREAD

**Issue by schaafjs** [DamascenoRafael/reminders-menubar#63]
Thank you for your work on this application!

Title pretty much sums it up.
It would be nice to have consistency between the Reminder.app and the listing in the menu bar.
Alternatively, alphabetical sorting (as currently implemented) or custom manual sorting could be provided.

**Comment by DamascenoRafael** [comment]
Hey @schaafjs. Thanks for the feedback!! 🤝 

I just released **version 1.9.0** 📦 where reminder lists are sorted like in Apple Reminders.
Can you check how it is in the new version?

Changing the order of the reminder lists was suggested in #21.
Please, if you have any additional comments, like custom manual sorting, post there.

**Comment by DamascenoRafael** [comment]
@schaafjs, not sure if I fully understand. Can you explain and give an example?

Previously only the lists were sorted alphabetically. So in the example below, in versions prior to 1.9.0, it would appear 'Dissertation', 'GitHub', 'Groceries', 'Payments', 'Reminders', 'Study' ...

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/9842644/189467577-c664f21d-bcfd-41b0-a880-57579b11d8bf.png">

The items/reminders (like 'Clear the mailbox 💌') do not appear in the same order as the Reminders.app. 
Would this be the change you were looking for?

- Send email to my advisor
- Look for awesome projects on GitHub
- Clear the mailbox 💌

But the items are also not in alphabetical order. Items appear according to priority (high, medium, low); If it has a due date it will be sorted by it and otherwise it will be sorted by the creation date.

**Comment by schaafjs** [comment]
Hi @DamascenoRafael,

thank you once again for the fast reply. The misunderstanding is completely mine.
I assumed you were talking about how the different reminders in a list were sorted, while you were actually talking about what I meant.
So, to answer your first question: yes, version 1.9.0 solves my issue.

Thanks so much for taking the time, and thanks again for this application! 😊

**Comment by DamascenoRafael** [comment]
Great!! I'm glad you like the app 😊

Please feel free to give any further feedback or suggestions!!

**Comment by schaafjs** [comment]
Will do, thanks!
