### ISSUE TITLE
Issue with filtering lists

### ISSUE THREAD

**Issue by quetzal-98** [DamascenoRafael/reminders-menubar#79]
HI, I just recognized that reminders of an excluded list are still appearing in the list of upcoming reminders. I was assuming that the list filter will also affect this section as well. I am having multiple lists for work and private topics and would like to see only reminders relevant for work at my office computer ;)

Thx!

**Comment by DamascenoRafael** [comment]
Hi @quetzal-98. Thanks for the feedback!
The behavior of the _Upcoming Reminders_ list is in line with the way it was designed, without applying any filters (similar to how the _Scheduled_ list in Apple's Reminders app works).
We can think of a setting to change this, but at the same time it would need to be clear that the  _Upcoming Reminders_ is being filtered, otherwise the app could make you miss some due date.

**Comment by DamascenoRafael** [comment]
I agree that smart lists could be a good solution.
Closing this issue as there is another issue to support smart lists (#44).
I'm currently investigating some workarounds for accessing information that isn't publicly available in the Apple API, so hopefully we'll get that implemented soon.
