### ISSUE TITLE
Feature Request: Clickable URL Link

### ISSUE THREAD

**Issue by LocheBC** [DamascenoRafael/reminders-menubar#90]
First of all, very much appreciate the app, thanks for your work!

Request is to have an option to access the URL associated with a reminder.

I use a keyboard shortcut (through Quick Action) to generate reminders from emails or web pages. It also includes a URL link to the email or the webpage. It achieves pretty much the same thing as using the "Share... Reminders" menu.

**Comment by DamascenoRafael** [comment]
Hi @LocheBC! Thanks for the feedback :)

Are you referring to a URL link in the dedicated URL field in the reminder? (as in the screenshot below from Apple Reminders)


<img width="816" alt="Screenshot 2022-12-13 at 23 44 56" src="https://user-images.githubusercontent.com/9842644/207492706-3c8d66ce-66ee-4079-b626-6337b313919c.png">

**Comment by LocheBC** [comment]
Yes that's correct!

Here's an example of my current list. It essentially shows the same as your Sample, except it's a URL to a specific email.

Also note the second item on my list, which has an email icon. Clicking it brings you to the email. This was created [using the Share Menu](https://www.idownloadblog.com/2016/03/29/create-reminder-mail-app-mac/), it has nothing to do with my Quick Action script. The URL field is empty, so it might be a different API to integrate this function as well. I personally don't use this (I only use URL), but just pointing it out.

![Screenshot 2022-12-13 at 7 44 00 PM](https://user-images.githubusercontent.com/120521429/207500532-2232fa3b-377b-4ef1-a938-7653ea7d099a.png)

**Comment by DamascenoRafael** [comment]
Great, thanks for the info! I will further investigate the APIs to try to implement these features.

**Comment by DamascenoRafael** [comment]
Hi @LocheBC.

The URL saved in a reminder is not publicly available in an Apple API ([see this thread on the apple developer forum](https://developer.apple.com/forums/thread/128140)).

Despite that I found a workaround on the internet to access that value and it worked! :) Since this is a workaround it will not be possible to edit the URL value, only view it.

About the example you showed where the Mail App icon appears, I still haven't figured out where this value is saved. I'll investigate a little more later to understand whether it will also be possible to display this type of link.

Anyway, the next version should already have the URL links.

<img width="660" alt="Screenshot 2023-01-02 at 16 18 52" src="https://user-images.githubusercontent.com/9842644/210271274-5c354e09-ee07-4129-9f66-9f0b332c6bdc.png">

**Comment by LocheBC** [comment]
You’re killing it Rafael!

Thanks for your work, will make your app much more useful for me. Looking forward for the next version.

Happy new year!

**Comment by DamascenoRafael** [comment]
@LocheBC I managed to get the link that goes to the mail.
The next version should support both URLs and links to Mail like you showed me before.

<img width="706" alt="Screenshot 2023-03-25 at 02 15 42" src="https://user-images.githubusercontent.com/9842644/227697822-243f7db8-9454-4450-8d37-3ce6090ea454.png">

**Comment by LocheBC** [comment]
Incredible! Thanks Rafael!Sent from my iPhoneOn Mar 25, 2023, at 00:22, Rafael Damasceno ***@***.***> wrote:﻿
@LocheBC I managed to get the link that goes to the mail.
The next version should support both URLs and links to Mail like you showed me before.
